name: sdugram_flutter
description: Sdugram app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # State Management
  flutter_bloc: ^8.1.3


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  injectable_generator: any
  auto_route_generator: ^7.3.2
  json_serializable: any

flutter:
  assets:
    - assets/images/
